"""Add deep analysis fields to unstructured_analysis

Revision ID: a5ce5c602b1d
Revises: f2e8320e1bc1
Create Date: 2025-11-10 11:41:39.928622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5ce5c602b1d'
down_revision: Union[str, Sequence[str], None] = 'f2e8320e1bc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unstructured_analysis', sa.Column('intent_type', sa.String(length=50), nullable=True))
    op.add_column('unstructured_analysis', sa.Column('decision_stage', sa.String(length=50), nullable=True))
    op.add_column('unstructured_analysis', sa.Column('conversion_probability', sa.Float(), nullable=True))
    op.add_column('unstructured_analysis', sa.Column('topics_discussed', sa.JSON(), nullable=True))
    op.add_column('unstructured_analysis', sa.Column('objections', sa.Text(), nullable=True))
    op.add_column('unstructured_analysis', sa.Column('clarity_score', sa.Float(), nullable=True))
    op.add_column('unstructured_analysis', sa.Column('trust_score', sa.Float(), nullable=True))
    op.add_column('unstructured_analysis', sa.Column('emotion_profile', sa.JSON(), nullable=True))
    op.add_column('unstructured_analysis', sa.Column('dominant_emotion', sa.String(length=30), nullable=True))
    op.add_column('unstructured_analysis', sa.Column('empathy_score', sa.Float(), nullable=True))
    op.add_column('unstructured_analysis', sa.Column('followup_priority', sa.String(length=20), nullable=True))
    op.alter_column('unstructured_analysis', 'entity_mentions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('unstructured_analysis', 'speech_acts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('unstructured_analysis', 'discourse_relations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('unstructured_analysis', 'deception_markers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('unstructured_analysis', 'conversation_phases',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('unstructured_analysis', 'dominance_score',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('unstructured_analysis', 'talk_ratio',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('unstructured_analysis', 'highlights',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('unstructured_analysis', 'themes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('unstructured_analysis', 'themes',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('unstructured_analysis', 'highlights',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('unstructured_analysis', 'talk_ratio',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('unstructured_analysis', 'dominance_score',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('unstructured_analysis', 'conversation_phases',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('unstructured_analysis', 'deception_markers',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('unstructured_analysis', 'discourse_relations',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('unstructured_analysis', 'speech_acts',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('unstructured_analysis', 'entity_mentions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('unstructured_analysis', 'followup_priority')
    op.drop_column('unstructured_analysis', 'empathy_score')
    op.drop_column('unstructured_analysis', 'dominant_emotion')
    op.drop_column('unstructured_analysis', 'emotion_profile')
    op.drop_column('unstructured_analysis', 'trust_score')
    op.drop_column('unstructured_analysis', 'clarity_score')
    op.drop_column('unstructured_analysis', 'objections')
    op.drop_column('unstructured_analysis', 'topics_discussed')
    op.drop_column('unstructured_analysis', 'conversion_probability')
    op.drop_column('unstructured_analysis', 'decision_stage')
    op.drop_column('unstructured_analysis', 'intent_type')
    # ### end Alembic commands ###
