"""Initial schema

Revision ID: f2e8320e1bc1
Revises: 
Create Date: 2025-11-04 15:31:52.674272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2e8320e1bc1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_call_logs_id'), 'call_logs', ['id'], unique=False)
    op.drop_constraint(op.f('call_logs_lead_id_fkey'), 'call_logs', type_='foreignkey')
    op.drop_constraint(op.f('call_logs_officer_id_fkey'), 'call_logs', type_='foreignkey')
    op.create_foreign_key(None, 'call_logs', 'leads', ['lead_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'call_logs', 'officers', ['officer_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_combined_analysis_id'), 'combined_analysis', ['id'], unique=False)
    op.drop_constraint(op.f('combined_analysis_structured_score_id_fkey'), 'combined_analysis', type_='foreignkey')
    op.drop_constraint(op.f('combined_analysis_officer_id_fkey'), 'combined_analysis', type_='foreignkey')
    op.drop_constraint(op.f('combined_analysis_unstructured_analysis_id_fkey'), 'combined_analysis', type_='foreignkey')
    op.drop_constraint(op.f('combined_analysis_lead_id_fkey'), 'combined_analysis', type_='foreignkey')
    op.create_foreign_key(None, 'combined_analysis', 'officers', ['officer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'combined_analysis', 'structured_scoring', ['structured_score_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'combined_analysis', 'leads', ['lead_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'combined_analysis', 'unstructured_analysis', ['unstructured_analysis_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_feature_store_keywords_id'), 'feature_store_keywords', ['id'], unique=False)
    op.drop_constraint(op.f('feature_store_keywords_analysis_id_fkey'), 'feature_store_keywords', type_='foreignkey')
    op.create_foreign_key(None, 'feature_store_keywords', 'unstructured_analysis', ['analysis_id'], ['id'], ondelete='CASCADE')
    op.alter_column('lead_scores', 'lead_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('lead_scores', 'officer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_lead_scores_id'), 'lead_scores', ['id'], unique=False)
    op.drop_constraint(op.f('lead_scores_officer_id_fkey'), 'lead_scores', type_='foreignkey')
    op.drop_constraint(op.f('lead_scores_lead_id_fkey'), 'lead_scores', type_='foreignkey')
    op.create_foreign_key(None, 'lead_scores', 'leads', ['lead_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lead_scores', 'officers', ['officer_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_leads_id'), 'leads', ['id'], unique=False)
    op.alter_column('officers', 'experience_years',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.create_index(op.f('ix_officers_id'), 'officers', ['id'], unique=False)
    op.create_index(op.f('ix_structured_scoring_id'), 'structured_scoring', ['id'], unique=False)
    op.drop_constraint(op.f('structured_scoring_lead_id_fkey'), 'structured_scoring', type_='foreignkey')
    op.create_foreign_key(None, 'structured_scoring', 'leads', ['lead_id'], ['id'], ondelete='CASCADE')
    op.alter_column('unstructured_analysis', 'keywords',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_unstructured_analysis_id'), 'unstructured_analysis', ['id'], unique=False)
    op.drop_constraint(op.f('unstructured_analysis_call_id_fkey'), 'unstructured_analysis', type_='foreignkey')
    op.create_foreign_key(None, 'unstructured_analysis', 'call_logs', ['call_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unstructured_analysis', type_='foreignkey')
    op.create_foreign_key(op.f('unstructured_analysis_call_id_fkey'), 'unstructured_analysis', 'call_logs', ['call_id'], ['id'])
    op.drop_index(op.f('ix_unstructured_analysis_id'), table_name='unstructured_analysis')
    op.alter_column('unstructured_analysis', 'keywords',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'structured_scoring', type_='foreignkey')
    op.create_foreign_key(op.f('structured_scoring_lead_id_fkey'), 'structured_scoring', 'leads', ['lead_id'], ['id'])
    op.drop_index(op.f('ix_structured_scoring_id'), table_name='structured_scoring')
    op.drop_index(op.f('ix_officers_id'), table_name='officers')
    op.alter_column('officers', 'experience_years',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.drop_index(op.f('ix_leads_id'), table_name='leads')
    op.drop_constraint(None, 'lead_scores', type_='foreignkey')
    op.drop_constraint(None, 'lead_scores', type_='foreignkey')
    op.create_foreign_key(op.f('lead_scores_lead_id_fkey'), 'lead_scores', 'leads', ['lead_id'], ['id'])
    op.create_foreign_key(op.f('lead_scores_officer_id_fkey'), 'lead_scores', 'officers', ['officer_id'], ['id'])
    op.drop_index(op.f('ix_lead_scores_id'), table_name='lead_scores')
    op.alter_column('lead_scores', 'officer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('lead_scores', 'lead_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'feature_store_keywords', type_='foreignkey')
    op.create_foreign_key(op.f('feature_store_keywords_analysis_id_fkey'), 'feature_store_keywords', 'unstructured_analysis', ['analysis_id'], ['id'])
    op.drop_index(op.f('ix_feature_store_keywords_id'), table_name='feature_store_keywords')
    op.drop_constraint(None, 'combined_analysis', type_='foreignkey')
    op.drop_constraint(None, 'combined_analysis', type_='foreignkey')
    op.drop_constraint(None, 'combined_analysis', type_='foreignkey')
    op.drop_constraint(None, 'combined_analysis', type_='foreignkey')
    op.create_foreign_key(op.f('combined_analysis_lead_id_fkey'), 'combined_analysis', 'leads', ['lead_id'], ['id'])
    op.create_foreign_key(op.f('combined_analysis_unstructured_analysis_id_fkey'), 'combined_analysis', 'unstructured_analysis', ['unstructured_analysis_id'], ['id'])
    op.create_foreign_key(op.f('combined_analysis_officer_id_fkey'), 'combined_analysis', 'officers', ['officer_id'], ['id'])
    op.create_foreign_key(op.f('combined_analysis_structured_score_id_fkey'), 'combined_analysis', 'structured_scoring', ['structured_score_id'], ['id'])
    op.drop_index(op.f('ix_combined_analysis_id'), table_name='combined_analysis')
    op.drop_constraint(None, 'call_logs', type_='foreignkey')
    op.drop_constraint(None, 'call_logs', type_='foreignkey')
    op.create_foreign_key(op.f('call_logs_officer_id_fkey'), 'call_logs', 'officers', ['officer_id'], ['id'])
    op.create_foreign_key(op.f('call_logs_lead_id_fkey'), 'call_logs', 'leads', ['lead_id'], ['id'])
    op.drop_index(op.f('ix_call_logs_id'), table_name='call_logs')
    # ### end Alembic commands ###
